Repository honeycombio/examples, pull requests merged in 2022-11, with the labels that each got.

#116 remove python-api example
  README.md
  python-api/Dockerfile
  python-api/README.md
  python-api/app.py
  python-api/docker-compose.yml
  python-api/requirements.txt
Labels: version: no bump, type: maintenance, merge at will, no-changelog

#117 remove ruby-wiki-tracing example
  README.md
  ruby-wiki-tracing/.rubocop.yml
  ruby-wiki-tracing/.rubocop_todo.yml
  ruby-wiki-tracing/README.md
  ruby-wiki-tracing/images/honeycomb.png
  ruby-wiki-tracing/images/trace.png
  ruby-wiki-tracing/views/edit.erb
  ruby-wiki-tracing/views/view.erb
  ruby-wiki-tracing/wiki.rb
Labels: version: no bump, type: maintenance, merge at will, no-changelog

#119 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#120 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
